export { postsReducer, postsActions } from './model/slice/posts/slice'
export { selectPosts } from './model/slice/posts/selectors'
export { getAllPosts } from './model/slice/posts/thunks/get/getAllPosts'
export { getPaginationPosts } from './model/slice/posts/thunks/get/getPaginationPost'
export { getPostToId } from './model/slice/posts/thunks/get/getPostToId'