export { servicesActions, servicesReducer } from './model/slice/services/slice'
export { selectUserServices } from './model/slice/services/selectors'
export { postsActions, postsReducer } from '../postState/model/slice/posts/slice'
export { AuthService } from './api/services/api.auth'
export { checkAuth } from './model/slice/services/thunks/auth/checkAuth'
export { login } from './model/slice/services/thunks/auth/login'
export { logout } from './model/slice/services/thunks/auth/logout'
export { signup } from './model/slice/services/thunks/auth/signup'
export { fastLogin } from './model/slice/services/thunks/auth/fastLogin'